name: "publish"
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Cleanup Disk
    #   if: matrix.platform == 'ubuntu-20.04'
    #   run: |
    #     df -h
    #     sudo rm -rf /usr/local/lib/android
    #     sudo rm -rf /usr/share/dotnet
    #     df -h

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Install Tauri dependencies
      run: |
        cargo install tauri-cli

    - name: Install Yew dependencies
      run: |
        rustup target add wasm32-unknown-unknown
        rustup target add wasm32-wasi
        cargo install --locked trunk

    - name: Install macOS intel & arm64 rust targets
      if: matrix.platform == 'macos-latest'
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin

    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Build the app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Build universal binary on macOS
        args: ${{ matrix.platform == 'macos-latest' && '--target universal-apple-darwin' || '' }}
        # The action automatically replaces \_\_VERSION\_\_ with the app version
        tagName: v__VERSION__
        tauriScript: cargo tauri
        releaseName: "RustyBudget v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
